### PR TITLE
Reduced lag for Forge and Gradio 4.0 - Removed infinite looping call to update

### PR DESCRIPTION
**Pull request by BenjaminSymons**
Removes the call to update component that seemingly ends in a loop and spams the console. Starts slowing down the UI due to the constant endpoint call (~1 per second)

### CODE REVIEW

**Comment by Natans8** [comment]
I get the following error when I use your fork:
```
CivitAI Browser+: Failed to start download: Failed to start download: {'id': '1', 'jsonrpc': '2.0', 'error': {'code': 1, 'message': "We encountered a problem while processing the option '--max-connection-per-server'."}}
```

**Comment by rktvr** [comment]
i also get the above error. it doesn't download anything.

**Comment by channelcat** [comment]
Using your findings I think I have a solve - it looks like all HTML change events work differently and frequently update without content changes, so I used hidden inputs to hold the HTML and trigger updates as expected in https://github.com/BlafKing/sd-civitai-browser-plus/pull/341

**Comment by rktvr** [comment]
i fixed it by just changing the max connections in the settings to something else (4, for me) and that fixed the error

**Comment by BlafKing** [comment]
Thanks for the pull request! I have been away for a few months and I'm looking to get back into maintaining this project!
I will compare this pull request with #341 to see which one fits best, I will also do some of my own testing so I'll probably either merge this or the other request soon 👍🏻 

Also about the aria2 update, this project uses a custom version of aria2 which allows for a higher amount of max connections per server, which is why some users are experiencing errors with the updated aria2.

**Comment by BenjaminSymons** [comment]
No worries @BlafKing. Turns out the model grid was constantly trying to update, and if you opened the update models tab or the download queue tab then the same thing happened - constant endpoint polling.

Naming the tabs helped remove the last laggy thing I could find

**Comment by BlafKing** [comment]
After reviewing, the #341 merge seemed to fit the project a bit better, keeping the custom aria2 compatibility as well as the method used to hide inputs to trigger updates at the right time.

I do want to thank you for your contribution regardless!
Helped me understand the current workings of the newer Forge versions a bit better and I'll definitely tweak some more things :)

Unfortunately I'll close this pull request, but please do not feel discouraged to contribute in the future, appreciate everyone who spends time on this project! <3

**Pull request closed without merging**
