### PR TITLE
Added subfolder creation based on first found civitai and some changes to previous pull to retain default codes/configuration while adding mine below the original

### PR DESCRIPTION
**Pull request by Lumerica**
Closed pull request #325 as I cannot seem to send a new pull request.

This new update I have reverted the sub folders I added. After thinking about it I was like why am i changing default things.
So instead I added additional sub folders instead and reverted the previous sub folders (14) back to before.

Additionally I have also added a feature to help me convenient automatically sort downloads depending on the civitai tag used.
However I can only do it based on a single. For now its based on first tag. In general, the authors would use the tag that makes most sense as first tag. But that is like 60% of the time.

So preferably we need a way to weight somehow which used tag makes most sense to be used. or maybe if there is a list that can be defined like if they match in this order, choose this or that tag instead as folder creation. Hope it can be evolved.

Also something more interesting, I noticed that each model somehow has a "hidden" tag used. Which seems to be automatically tagged by civitai. I noticed that as I was first trying to use  `item['tags'][0]`
Then figured that its not even in the civitai used by the author.

Ps.Apologies for the messy codes, I am really not a programmer I used many many comments and prints to debug etc. They are still in the code. I left some there hoping that maybe it might help someone to understand what I was trying to do lol

### CODE REVIEW

**Comment by Lumerica** [comment]
Today stumbled upon a model that got a Pipe character in the model and noticed that it did not get cleaned/replaced.
So I added a replace function for that.

Additionally the commit to support tags in folder creation. I encountered a checkpoint that does not have an automatic civitAI tag. Had a hard time to at first figure whats happening. So I adjusted the code i wrote. So now it supports that as well

And here is the example of a checkpoint with no automatic tagged by civitai:
https://civitai.com/models/289633
And this checkpoint even worse, got no civitai automatic tag or author tag:
https://civitai.com/models/33687
Anway, now both are also supported. of course if someone use the tag name as sub-folder creation:
image
image

Oh I forgot to show the sub folder options... at least should have included a screenshot to make it easier for you to review i guess. As to weather you want to adapt it... you are the owner of this extension :)
image


All that say, i dont know how to merge [this ]( https://github.com/Lumerica/sd-civitai-browser-plus_fix/commit/3a2fc484620659d3d3f02ecaa24b15994280b15a) new commit to this "pull request" #343 .
You can see it here:

**Comment by BlafKing** [comment]
Thanks for your contribution!
However, I'd like to avoid adding (even) more options to the sub folder options.

I'll probably have a look at reworking how sub folders are used all together, since it's currently really messy, and it'll only get worse down the road if the current system is kept :,)

Thanks regardless for taking the time to make a pull request though! but I'll close this since I'll likely write a new system all together soon.

**Comment by BlafKing** [comment]
I'll make sure to include a little fix for removing trailing/leading spaces!
However about the exclusing of the pipe character, that should already be done? since the code contains:
```
illegal_chars_pattern = r'[\\/:*?"<>|]'
```

I saw you changed it to:
```
illegal_chars_pattern = r'[\\/:*?"<>|\^]'
```

But the `^` is not an illegal character for windows afaik, regardless I'll add a check that removes trailing and leading spaces 👍🏻

**Comment by Lumerica** [comment]
Not sure if these things are called "function" or "method" in python.
But the problem is that it does not get handled. So only replace works.
You can test it searching for few models with a pipe in model name and version name.

As for `^` Yep you are right its not illegal, I thought i removed that from the version i published.

**Comment by Lumerica** [comment]
Ah by the way, its a bit off topic, but i mentioned in the discussion section. However since you are back and I caught your attention, currently models are being downloaded without the critical version information being downloaded at all.
The section "About version" on Civitai actually provides a lot of information depending on the author of course. But often times when a good model is being shared the information are in there.

Other stuff that might give you some more idea about improvements are here which are too impossible for me pickup as a non programmer (lol):
https://github.com/BlafKing/sd-civitai-browser-plus/discussions/323

**Comment by BlafKing** [comment]
I'll make sure to go through all the feature suggestions once I'm done with fixing (most of) the bugs!
No guarantee that they'll be added though but I'll look into it :)

**Pull request closed without merging**
